modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/JamCoreModding/right-click-harvest/issues"

[[mods]]
modId = "rightclickharvest"
version = "${file.jarVersion}"
displayName = "Right Click Harvest"
displayURL = "https://github.com/JamCoreModding/right-click-harvest"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Right click crops to harvest them - with style.
'''

[[dependencies.rightclickharvest]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rightclickharvest]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rightclickharvest]]
modId = "architectury"
type = "required"
versionRange = "[11.0.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.rightclickharvest]]
modId = "jamlib"
type = "required"
versionRange = "[1.0.3+1.20.4,)"
ordering = "AFTER"
side = "BOTH"
